### ISSUE TITLE
maven nexus 私服不可用了吗?

### ISSUE THREAD

**Issue by aillamsun** [gudaoxuri/dew#129]
[INFO] [ERROR] Failed to execute goal ms.dew:dew-maven-plugin:2.0.0-SNAPSHOT:release (default-cli) on project todo-parent: Execution default-cli of goal ms.dew:dew-maven-plugin:2.0.0-SNAPSHOT:release failed: Could not transfer artifact ms.dew.devops.it:todo-common:jar:2.0.0-SNAPSHOT from/to trc-snapshots (http://121.41.17.205:18081/nexus/content/repositories/snapshots/): Connect to 121.41.17.205:18081 [/121.41.17.205] failed: Operation timed out (Connection timed out)

**Comment by gudaoxuri** [comment]
http://121.41.17.205:18081 是我们公司的内部Maven仓库地址，你在跑IT或Unit Test时将devops/devops-test.properites替换为你自身环境的配置。

**Comment by aillamsun** [comment]
感谢回答
