### ISSUE TITLE
如何用Istio部署

### ISSUE THREAD

**Issue by dick318** [gudaoxuri/dew#169]
如何用Istio部署

**Comment by sunyl527** [comment]
可参考Istio官方文档，在Dew DevOps方案之上，增量添加所需配置尝试一下。https://istio.io/docs/examples/bookinfo/

**Comment by dick318** [comment]
希望能有一些示例教程，这方面的资料感觉有点少，希望能完善一下，比如springcloud的网关、服务注册这些要不要移除

**Comment by sunyl527** [comment]
https://mp.weixin.qq.com/s/XX4qSBwRBAX-4pYXtd4Q8A
